name = "Blink"
level = 1
type_class = "Mage"
exp = 0
health = 10
health_max = 10
mp = 10
mp_max = 10
wood = 38
stone = 30
iron_ore = 15
iron = 0
gold_ore = 20
gold = 0
money = 0
weapon = "Wand"
weapon_inventory = ['Wand', 'Wand']
armor = ""
armor_inventory = []
inventory = []
world = "Green Field"
quests_completed = []
quest_current = "none"